apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clarityci-website
  namespace: clarityci
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - clarityci.com
    - www.clarityci.com
    secretName: clarityci-website-tls
  rules:
  - host: clarityci.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: clarityci-website
            port:
              number: 80
  - host: www.clarityci.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: clarityci-website
            port:
              number: 80
